export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_SEARCH_MEETING_LIST = 'SET_SEARCH_MEETING_LIST'
export const SET_SEARCH_STR = 'SET_SEARCH_STR'
export const SET_NEWEST_MEETING_LIST = 'SET_NEWEST_MEETING_LIST'
